### PR TITLE
Add picom config for VM and correctly start picom in xmonad.hs

### PR DESCRIPTION
**Pull request by Kellegram**
In xmonad.hs, picom was started with picom -f which simply starts picom with fade overriden to be enabled, but fade is not even set up. Additionally, to use experimental backends, it has to be started like in the commit, in my testing from the past I have found that putting the option inside the config does not function as expected.

I also made a decently optimised picom.conf that works in a VM. For that, picom should NOT be started with experimental-backends however, will add a note on that.

### CODE REVIEW

**Comment by Axarva** [comment]
Seems great, although I'd change the folder name to something like just `vm` then tell the user to go through it if they use a vm.

**Review by Axarva — COMMENTED** [review]
Hmm, you did remove the `-f` option to picom which means window fading will now be disabled?

**Comment by Kellegram** [comment]
> Hmm, you did remove the `-f` option to picom which means window fading will now be disabled? 

-f is normally just used to enable defaults for fade.If you want fade, you can configure it in picom.conf, no need to call it with -f.

**Comment by Axarva** [comment]
Thank you!

**Pull request merged**
