### PR TITLE
Move one-line scripts to xmonad.hs

### PR DESCRIPTION
**Pull request by Kellegram**

### CODE REVIEW

**Comment by Kellegram** [comment]
I tried some of these in the past, but do test if all the ones I changed work, the eww ones should at the very least. The notify ones I am not sure how to add since they lack a closing quotation mark. Perhaps two apostrophes would close it but no idea.

**Comment by Kellegram** [comment]
Rest of the scripts can probably be put in xmonad folder then imported to xmonad instead, would be much cleaner than using bin, will investigate, so this should stay as draft PR for now.

**Comment by Kellegram** [comment]
Ok, this is ready now.

**Comment by Axarva** [comment]
Looks great. And as always, thank you so much once again!

**Pull request merged**
