### PR TITLE
Change line 328 on config/eww-1920/eww.scss to use ~ instead of a specific user. 

### PR DESCRIPTION
**Pull request by Jimmysit0**
Change line 328 to use $HOME instead of your specific user. (easier for people who doesn't want to edit any of your config)

### CODE REVIEW

**Comment by Jimmysit0** [comment]
You could also use ~/config/eww/images/p.png, like eww-1366 does, personally I would use $HOME

**Comment by Axarva** [comment]
I'm pretty sure this doesn't work, and that you need the full path to the image.

This is the result when I try the proposed solution.
image

**Comment by Jimmysit0** [comment]
Should work now

**Comment by Axarva** [comment]
Still no change on my machine. Could you show results on your own machine?
I tried updating my eww binary just in case it was a new feature, yet I have had no good results.

**Comment by Jimmysit0** [comment]
On my machine it works fine, does the 1366 ver work for you? if it does then this patch should work as well

**Comment by Axarva** [comment]
Sorry for the late reply
Nope, that doesn't work either

**Comment by Axarva** [comment]
I'll merge this although it doesn't fix the issue, because it at least conceals a contributor's username they possibly left due to a little carelessness.

Thank you anyways!

**Comment by Jimmysit0** [comment]
Woops, I completely forgot about this pull request and guessed it was closed, I'm sorry about it tho, I think it wasn't necessary to merge, specially if it doesn't fix the issue :(

**Comment by Axarva** [comment]
Just got tired

Well, it wasn’t working either ways and I’d feel bad about closing a PR so merged!

**Pull request merged**
